version: "3.9"

services:
  seu-blog:
    container_name: seu-blog
    build:
      context: .
    ports:
      - "8085:8080"
    volumes:
      - seu-blog-logs:/app/logs
    networks:
      - seu-blog-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seublogdb
      SPRING_DATASOURCE_USERNAME: seuuser
      SPRING_DATASOURCE_PASSWORD: seupassword

  postgres:
    image: postgres:16
    container_name: seu-postgres
    restart: always
    environment:
      POSTGRES_DB: seublogdb
      POSTGRES_USER: seuuser
      POSTGRES_PASSWORD: seupassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - seu-blog-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: seu-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@seu.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - seu-blog-network

volumes:
  seu-blog-logs:
  postgres-data:

networks:
  seu-blog-network:
    driver: bridge
