spring.application.name: seu-blog

spring:
#  profiles:
#    active: dev
  datasource:
    username: seuuser
    password: seupassword
    url: jdbc:postgresql://postgres:5432/seublogdb


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  sql:
#    init:
#      mode: always
#      platform: postgresql
#      schema-locations: classpath:sql/schema.sql

keys.access-private-token: keys/access-private
keys.access-public-token: keys/access-public
keys.refresh-public-token: keys/refresh-public
keys.refresh-private-token: keys/refresh-private

logging:
  level:
    org.springframework:
      security: debug
