spring.application.name: seu-blog

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5168/seu-blog
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  sql:
#    init:
#      mode: always
#      platform: postgresql
#      schema-locations: classpath:sql/schema.sql
